databaseChangeLog:
  - changeSet:
      id: insert-random-values
      author: a.bronnikov
      changes:
        - insert:
            tableName: "wallet"
            columns:
              - column:
                  name: "wallet_id"
                  valueComputed: "uuid_generate_v4()"
              - column:
                  name: "balance"
                  valueComputed: "ROUND((RANDOM() * 1000)::numeric, 2)"

        - insert:
            tableName: "wallet"
            columns:
              - column:
                  name: "wallet_id"
                  valueComputed: "uuid_generate_v4()"
              - column:
                  name: "balance"
                  valueComputed: "ROUND((RANDOM() * 1000)::numeric, 2)"

        - insert:
            tableName: "wallet"
            columns:
              - column:
                  name: "wallet_id"
                  valueComputed: "uuid_generate_v4()"
              - column:
                  name: "balance"
                  valueComputed: "ROUND((RANDOM() * 1000)::numeric, 2)"